version: "3.8"

services:
  localstack:
    image: localstack/localstack:1.0.3
    container_name: localstack
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:4566" ]
    ports:
      - "4566:4566"
    environment:
      SERVICES: sns, sqs
      AWS_DEFAULT_REGION: eu-west-2
#      HOSTNAME_EXTERNAL:localstack # TODO - place back
    volumes:
      - ./localstack:/docker-entrypoint-initaws.d
